### PR TITLE
Add localized strings, update french strings and remove "language.mo" files

### PR DESCRIPTION
**Pull request by Etraga**
Added some localized strings.

I also have updated french strings but I don't know how to submit them.

### CODE REVIEW

**Comment by Etraga** [comment]
Thanks, I'll make a PR asap. You already Can merge this one.

Thanks for your work,
Etraga

**Comment by Etraga** [comment]
PR updated. I also have removed "language.po" files from git, and update french translation file

**Comment by Etraga** [comment]
Updated to match with recent changes

**Comment by Etraga** [comment]
@Bob123a1 any feedback about this PR?

**Comment by Bob123a1** [comment]
@Etraga I was testing it out yesterday with the different languages game info text and it didn't quite match certain strings, however I will merge it now as I know how to fix that issue

**Comment by Bob123a1** [comment]
Thanks for your work !

**Pull request merged**
